server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?enabledTLSProtocols=TLSv1.2&characterEncoding=UTF-8&useUnicode=true&useSSL=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowMultiQueries=true&sessionVariables=transaction_isolation='READ-COMMITTED'&useAffectedRows=true
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-init-sqls: set names utf8mb4;
  redis:
    timeout: 200s
    host: localhost
    port: 6379

  cache:
    type: redis
    redis:
      cache-null-values: false
  rabbitmq:
    host: 192.18.2.231
    username: admin
    password: admin
    port: 5672
    #配置虚拟机
    virtual-host: /sunke
    ssl:
      verify-hostname: false
      enabled: false
      validate-server-certificate: false
    connection-timeout: 5s
    #消息开始手动确认
    listener:
      simple:
        auto-startup: true
        concurrency: 20
      direct:
        auto-startup: true

pagehelper:
  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql



